### ISSUE TITLE
createObject cannot determine class for union types

### ISSUE THREAD

**Issue by jrajamaki** [erickskrauch/phpstan-yii2#3]
To reproduce the problem:
```PHP
class Foo extends \yii\base\Component {}
class Bar extends \yii\base\Component {}

foreach ([Foo::class, Bar::class] as $class) {
    Yii::createObject([
        'class' => $class,
    ]);
}
```
This will report error `Configuration params array must have "class" or "__class" key` even if the configuration params array has `'class'` entry. The problem seems to be that `YiiConfigHelper::findClass` cannot determine the proper class for object when multiple classes are possible, i.e. `$class` has union type.

```PHP
Yii::createObject($class);
```
inside the `foreach` seems to work properly.

**Comment by erickskrauch** [comment]
Thanks for the report. I'll look into it as soon as I have time.

**Comment by jrajamaki** [comment]
Thanks for quick resolution, it might not be ultimate solution but at least I'll get rid of those errors.

With your work Stan analysis is much better in Yii2 projects, I appreciate it.
