### ISSUE TITLE
Update to phpstan 1.11

### ISSUE THREAD

**Issue by pgrond** [erickskrauch/phpstan-yii2#5]
The composer file references phpstan ^1.10, but in require-dev version 1.11 is referenced. 
Can the entry in require also be bumped to ^1.11?

**Comment by erickskrauch** [comment]
Hello. The current version specification does not restrict you from using version 1.11.0: `^1.10` means `>=1.10.0 && <2.0.0`. If you are talking about dev dependencies, I will update those later when I get back to active development on this project.
